# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('handle', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('profile_photo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('date_founded', models.CharField(max_length=9)),
                ('header_photo', models.CharField(max_length=100)),
                ('artists', models.ManyToManyField(to='viewer.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=9)),
                ('path', models.CharField(max_length=100)),
                ('filetype', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pack',
            name='pieces',
            field=models.ManyToManyField(to='viewer.Piece'),
        ),
        migrations.AddField(
            model_name='group',
            name='packs',
            field=models.ManyToManyField(to='viewer.Pack'),
        ),
        migrations.AddField(
            model_name='artist',
            name='pieces',
            field=models.ManyToManyField(to='viewer.Piece'),
        ),
    ]
