# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='packs',
            field=models.ManyToManyField(to='viewer.Pack'),
        ),
    ]
