# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_artist_packs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='packs',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='group',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='group',
            name='packs',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='pieces',
        ),
        migrations.AddField(
            model_name='artist',
            name='groups',
            field=models.ManyToManyField(to='viewer.Group'),
        ),
        migrations.AddField(
            model_name='pack',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viewer.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='artists',
            field=models.ManyToManyField(to='viewer.Artist'),
        ),
        migrations.AddField(
            model_name='piece',
            name='pack',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viewer.Pack'),
            preserve_default=False,
        ),
    ]
