# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20180918_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pack',
            name='file_path',
            field=models.FilePathField(default=None, match='foo.*', path='home/images', recursive=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pack',
            name='slug',
            field=models.SlugField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pack',
            name='upload',
            field=models.FileField(default=None, upload_to='home/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='file_path',
            field=models.FilePathField(default=None, match='foo.*', path='home/images', recursive=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='slug',
            field=models.SlugField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='upload',
            field=models.FileField(default=None, upload_to='home/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_photo',
            field=models.ImageField(upload_to='home/images/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_founded',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='header_photo',
            field=models.ImageField(upload_to='home/images/'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=models.DateField(),
        ),
    ]
