# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20180918_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='filetype',
            new_name='graphics_format',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='path',
        ),
    ]
