# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import viewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20180918_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_photo',
            field=models.ImageField(upload_to=viewer.models.get_profile_image_path),
        ),
        migrations.AlterField(
            model_name='group',
            name='header_photo',
            field=models.ImageField(upload_to=viewer.models.get_profile_image_path),
        ),
        migrations.AlterField(
            model_name='pack',
            name='upload',
            field=models.FileField(upload_to=viewer.models.get_pack_path),
        ),
    ]
