# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import viewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_auto_20180918_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='upload',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='upload',
        ),
        migrations.AddField(
            model_name='piece',
            name='file',
            field=models.FileField(default=None, upload_to=viewer.models.get_piece_path),
            preserve_default=False,
        ),
    ]
