# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import viewer.models
import viewer.storage


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_auto_20180918_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_photo',
            field=models.ImageField(blank=True, storage=viewer.storage.OverwriteStorage(), upload_to=viewer.models.get_profile_image_path),
        ),
        migrations.AlterField(
            model_name='group',
            name='header_photo',
            field=models.ImageField(blank=True, storage=viewer.storage.OverwriteStorage(), upload_to=viewer.models.get_profile_image_path),
        ),
        migrations.AlterField(
            model_name='pack',
            name='file',
            field=models.FileField(storage=viewer.storage.OverwriteStorage(), upload_to=viewer.models.get_pack_path),
        ),
        migrations.AlterField(
            model_name='piece',
            name='file',
            field=models.FileField(storage=viewer.storage.OverwriteStorage(), upload_to=viewer.models.get_piece_path),
        ),
    ]
