# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_auto_20180919_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='groups',
            field=models.ManyToManyField(blank=True, to='viewer.Group'),
        ),
    ]
