# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_auto_20180919_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='artists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.Artist'),
        ),
    ]
